apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/component: manager
resources:
  - ../configurations/prometheus-operator
  - clusterrole.yaml
  - clusterrole-edit.yaml
  - deployment.yaml
  - lease.yaml
  - monitor.yaml
  - pdb.yaml
  - rbac.yaml
  - role.yaml
  - service.yaml
  - mutatingwebhookconfiguration.yaml
  - validatingwebhookconfiguration.yaml
configMapGenerator:
  - name: manager-config
    options:
      disableNameSuffixHash: true
  - name: default-monitoring
    options:
      disableNameSuffixHash: true
      labels:
        cnpg.io/reload: ""
    files:
      - queries=files/queries.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: PGBOUNCER_IMAGE_NAME
                    # renovate: datasource=docker
                    value: ghcr.io/cloudnative-pg/pgbouncer:1.25.1@sha256:f26dab8d644049458fec2eb631a4b67fa79b6c9f0da02bbdc5f56a5f3255561c
                  - name: POSTGRES_IMAGE_NAME
                    # renovate: datasource=docker
                    value: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie@sha256:83eed1b1712edd8d881e5cf1b989519b8863f123aa9e2232fffaef5afa20a0c3
images:
  - name: ghcr.io/cloudnative-pg/cloudnative-pg
    newTag: 1.29.1@sha256:0dfff19ba7b52ca25851a1010028b6940fff2e233290465af1cfb08a5f3f4661
replacements:
  - source:
      kind: Deployment
      name: manager
      fieldPath: spec.template.spec.containers.[name=manager].image
    targets:
      - select:
          kind: Deployment
          name: manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=OPERATOR_IMAGE_NAME].value
