apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/component: manager
resources:
  - clusterrole.yaml
  - clusterrole-edit.yaml
  - deployment.yaml
  - lease.yaml
  - pdb.yaml
  - rbac.yaml
  - role.yaml
  - service.yaml
  - mutatingwebhookconfiguration.yaml
  - validatingwebhookconfiguration.yaml
configMapGenerator:
  - name: manager-config
    options:
      disableNameSuffixHash: true
  - name: default-monitoring
    options:
      disableNameSuffixHash: true
      labels:
        cnpg.io/reload: ""
    files:
      - queries=files/queries.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: POSTGRES_IMAGE_NAME
                    # renovate: datasource=docker
                    value: ghcr.io/cloudnative-pg/postgresql:17.2@sha256:0f82f3fefb87c2657d47c70c9e6b972c6f26c6b009627fc80d9ee3c3b920b92b
images:
  - name: ghcr.io/cloudnative-pg/cloudnative-pg
    newTag: 1.24.1@sha256:3ffc9b353804b050741c145ddc7b71a418c21153e6fc92c5d9dabac11d7a5257
replacements:
  - source:
      kind: Deployment
      name: manager
      fieldPath: spec.template.spec.containers.[name=manager].image
    targets:
      - select:
          kind: Deployment
          name: manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=OPERATOR_IMAGE_NAME].value
