apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/postgis-containers/image-catalogs?ref=29d0258f78e297d8cced4f554f1e3c3b114733b3 # branch=main
