apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/postgis-containers/image-catalogs?ref=7848cc2f06bfc87a5e3f70bd2fde0ea88df03fd3 # branch=main
