apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/postgis-containers/image-catalogs?ref=282fa41dba195957dc1b5c9900b76459068f1151 # branch=main
