apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/artifacts/image-catalogs?ref=c267561c9a5cf85607ea29e3bb6dbc7028d4b791 # branch=main
