apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/artifacts/image-catalogs?ref=7619dbe8bcde83077c6a912b5d0aff5063d56d9c # branch=main
